// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZRSHLelbEKK1pD8fViIHhc_vPBQ0fFEs',
    appId: '1:5837474353:web:39cb6b69c270ed850aa310',
    messagingSenderId: '5837474353',
    projectId: 'social-app-335d1',
    authDomain: 'social-app-335d1.firebaseapp.com',
    storageBucket: 'social-app-335d1.firebasestorage.app',
    measurementId: 'G-8XHF9PWQ69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAjpP0EzP1pfqFQirElowUpYeCYJeaKUc',
    appId: '1:5837474353:android:79585597425b4b060aa310',
    messagingSenderId: '5837474353',
    projectId: 'social-app-335d1',
    storageBucket: 'social-app-335d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtJmg2_iMtEhldcCOCOkalL7oHGXcl0I8',
    appId: '1:5837474353:ios:e537e305e2e45f430aa310',
    messagingSenderId: '5837474353',
    projectId: 'social-app-335d1',
    storageBucket: 'social-app-335d1.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );
}
